apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagesearch
  labels:
    app: imagesearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagesearch
  template:
    metadata:
      labels:
        app: imagesearch
    spec:
      containers:
      - name: imagesearch
        image: pz/image_search:latest
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: imagesearch
  labels:
    app: imagesearch
spec:
  type: NodePort
  selector:
    app: imagesearch
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30050